# Generated by Django 3.1.1 on 2020-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=250)),
                ('phone', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
