# Generated by Django 3.1.1 on 2020-11-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201128_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
