# Generated by Django 3.1.1 on 2020-11-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201129_0831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
